<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>WarcraftLegacies.Source</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="WCSharp.War3Net.Build" Version="5.7.3" />
      <PackageReference Include="WCSharp.War3Net.Build.Core" Version="5.7.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MacroTools.Shared\MacroTools.Shared.csproj" />
        <ProjectReference Include="..\MacroTools\MacroTools.csproj" />
        <ProjectReference Include="..\WarcraftLegacies.Generated\WarcraftLegacies.Generated.csproj" />
        <ProjectReference Include="..\WarcraftLegacies.Shared\WarcraftLegacies.Shared.csproj" />
    </ItemGroup>

</Project>
